### ISSUE TITLE
Tag release with proper version number to dockerhub

### ISSUE THREAD

**Issue by zdtsw** [nikolaik/docker-python-nodejs#1]
Hi,

Could you tag your builds with proper version number but not only latest for all images?
We are trying to use your image and we get different node and npm versions every here and there. 

Thanks!

Brs
Wen

**Comment by nikolaik** [comment]
@zdtsw Hi there! As you might have guessed, I have little time to setup proper tagging of builds for the matrix of python, pipenv, node, npm and yarn versions that are available. I suggest you checkout the images that circleci provides over at https://circleci.com/docs/2.0/circleci-images/#python for now

**Comment by nikolaik** [comment]
@zdtsw I finally found the time to do proper building and taging of all the supported versions of python and node.js.

**Comment by zdtsw** [comment]
thanks!
