### ISSUE TITLE
Messing with Pterodactyl

### ISSUE THREAD

**Issue by tudubucket** [nikolaik/docker-python-nodejs#103]
Hi, I've installed `nikolaik/python-nodejs` docket image into my pterodactyl server. And its seems like running in directory `/` instead of `/home/container/`. 

![image](https://github.com/nikolaik/docker-python-nodejs/assets/106295287/87a84caa-0b19-4b40-95db-27a08c487dd1)

I'm still new in this, is there any way to solve this problem? And how do i run file through startup command in Pterodactyl panel?

**Comment by nikolaik** [comment]
How are you installing and running the docker image? If you are inheriting from `nikolaik/python-nodejs` using your own `Dockerfile` then you can either set a working directory using [`WORKDIR /home/container`](https://docs.docker.com/engine/reference/builder/#workdir) or you might want to change into that directory before running more commands [`RUN cd /home/container`](https://docs.docker.com/engine/reference/builder/#run)

I would ask followup questions in the [pterodactyl community discord](https://discord.gg/pterodactyl)
