### ISSUE TITLE
python2.7 and nodejs 14

### ISSUE THREAD

**Issue by moish83** [nikolaik/docker-python-nodejs#13]
Hi,
Will you create the combo in the title to be built automatically?
Thanks

**Comment by nikolaik** [comment]
> Hi,
> Will you create the combo in the title to be built automatically?
> Thanks

Hi @moish83 I'm sorry to say that I will not add back any python 2.7 version to the build matrix. You can read more on the reasoning behind this at [python3statement.org](https://python3statement.org/).

* What is your use case for this combo?

**Comment by moish83** [comment]
@nikolaik I know python2.7 is EOL. my usecase is the need to upgrade nodejs version, however the py.test infrastructure is still not migrated to > python3

**Comment by moish83** [comment]
Can you give me the command to create this combo by myself? to use it till we move to python3 for the unit test infrastructure?

**Comment by moish83** [comment]
I managed to modify the scrpit to create the desired combo

**Comment by nikolaik** [comment]
Nice. You probably ended up with a Dockerfile looking something like this then:
```
FROM python:2.7
# Install node prereqs, nodejs and yarn
# Ref: https://deb.nodesource.com/setup_14.x
# Ref: https://yarnpkg.com/en/docs/install
RUN \
  echo "deb https://deb.nodesource.com/node_14.x buster main" > /etc/apt/sources.list.d/nodesource.list && \
  wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
  wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  apt-get update && \
  apt-get install -yqq nodejs=$(apt-cache show nodejs|grep Version|grep nodesource|cut -c 10-) yarn && \
  apt-mark hold nodejs && \
  pip install -U pip && pip install pipenv && \
  npm i -g npm@^6 && \
  rm -rf /var/lib/apt/lists/*
```

**Comment by moish83** [comment]
kind of, I've built the alpine variant
