### ISSUE TITLE
DNS Lookup Error

### ISSUE THREAD

**Issue by usmansagri** [nikolaik/docker-python-nodejs#146]
Hi Guys,

Good day!

I am unable to build the application and getting DNS Lookup error on executing `RUN apk -U upgrade` in my Dockerfile.

Kindly help.

<img width="691" alt="DNS Error" src="https://github.com/nikolaik/docker-python-nodejs/assets/32294868/dc5bf1bf-5325-46e9-8896-c0c3fb60e7ce">

**Comment by usmansagri** [comment]
I am using nikolaik/python-nodejs:python3.10-nodejs18-alpine

**Comment by usmansagri** [comment]
Hi @nikolaik,

Good day!

Can you please guide?

Few months back I did not face this issue but now I am unable to build the application itself.

**Comment by nikolaik** [comment]
`DNS lookup error`s are most likely a result of a network issue outside the scope of this specific docker image.

Some things to try:
- Restart your docker daemon
- Restart your machine/VM
- Restart your network hardware
- Double check your macines' DNS configuration
- Disable/restart VPN
- Try running the build on another machine
- Try switching to another network

Good luck!
