### ISSUE TITLE
Add -slim debian variant

### ISSUE THREAD

**Issue by nikolaik** [nikolaik/docker-python-nodejs#15]

**Comment by GOST-UA** [comment]
Are you planning to implement this feature? If it's needed I could try to help with this.

**Comment by nikolaik** [comment]
@GOST-UA Should be fixed in 253d19838e31cfaa21897eb546dc76fef332090b Did the new images work like you expected?

**Comment by GOST-UA** [comment]
Thanks for adding slim versions. Unfortunately, for my case make is also required which seems to absent in the slim version. I am too lazy to create my own image on top of yours so I stayed on buster image 😄
