### ISSUE TITLE
python3.11-nodejs20 image contains Node v21.5

### ISSUE THREAD

**Issue by saschatimme** [nikolaik/docker-python-nodejs#154]
Looking at https://hub.docker.com/layers/nikolaik/python-nodejs/python3.11-nodejs20/images/sha256-79587bbeae9a6ca2788b132d3ca616bb4292ae0cacc3e64c78be3116ce857443?context=explore

you see  that NODE_VERSION is dynamically set via

```
NODE_VERSION="$(curl -fsSL https://nodejs.org/dist/latest/SHASUMS256.txt | head -n1 | awk '
```

but this returns `v21.5.0`. Since the above Docker image was rebuilt only yesterday this now contains the completely wrong version...

**Comment by saschatimme** [comment]
Thank you for the quick fix :)

**Comment by nikolaik** [comment]
The images should be rebuilt with the correct version now, do you want to verify?
