### ISSUE TITLE
/usr/local/bin/poetry is a symlink to /root/.poetry/bin/poetry so you can't install packages via poetry as a non root user

### ISSUE THREAD

**Issue by myers** [nikolaik/docker-python-nodejs#19]
I would suggest installing poetry via `pip install poetry`

**Comment by nikolaik** [comment]
I've update the way poetry is install in https://github.com/nikolaik/docker-python-nodejs/pull/30 and we now to symlink to /opt/poetryvenv/bin/poetry instead. Hope this fixes your issue
