### ISSUE TITLE
Please publish stable version tags to docker hub

### ISSUE THREAD

**Issue by lachlanhunt** [nikolaik/docker-python-nodejs#2]
I'd like to be able to use this Docker image, but I need to have some control over when the build system uses new versions of node and python. Thus I cannot use the `latest` tag because you could bump the versions of node or python at any time.

Can you please publish the image to docker hub with a more stable tag that indicates the versions of node and python included?

**Comment by nikolaik** [comment]
@lachlanhunt Great suggestion. Are you mostly interested in tags with newer combinations of node and python versions, something like the following labels?
- `python3.6-node8`
- `python3.7-node8`
- `python3.6-node10`
- `python3.7-node10`
- `python3.6-node11`
- `python3.7-node11`

**Comment by nikolaik** [comment]
This should now be fixed. Let me know if you have any issues with the new tags 🤗
