### ISSUE TITLE
Publish image to Amazon ECR Public Gallery?

### ISSUE THREAD

**Issue by icj217** [nikolaik/docker-python-nodejs#20]
More of a request than an issue. It would be nice to publish the image to public ECR as well for those of us who have AWS-based workloads and want to avoid Docker Hub pull rate limiting

**Comment by nikolaik** [comment]
I think I'll gauge interest for this before acting on it. In the meantime, you can probably use this image as a base and push your own to ECR fairly easily using circleci cronjobs f.ex

**Comment by nikolaik** [comment]
Closing this because of lack of interest

**Comment by viyatgandhi** [comment]
@nikolaik I will second this for AWS ECR. Until then I will push base image to private ECR
