### ISSUE TITLE
How do I add and set up cron

### ISSUE THREAD

**Issue by Yangsl520** [nikolaik/docker-python-nodejs#25]
How do I add and set up cron？

**Comment by nikolaik** [comment]
Setting up cron sounds like a question which is outside the scope of this docker image.

To run a cronjob in this docker image I suggest adapting the answer in this article: https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

**Comment by Yangsl520** [comment]
> 设置cron听起来像是一个问题，这是在这个码头工人图像的范围之外。
> 
> 要在此码头工人图像中运行一个 cronjob， 我建议改编本文中的答案： https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

Thank you！
