### ISSUE TITLE
Error setting WORKDIR on latest image

### ISSUE THREAD

**Issue by owlas** [nikolaik/docker-python-nodejs#31]
Using the latest docker image, I've started getting errors on the second line of my Dockerfile: 

https://github.com/lightdash/lightdash/blob/a14e470db04bffe791fa07d9484695bd8b3ae38b/dockerfile#L1-L3

when setting `WORKDIR` I get the following error during build (I'm using `DOCKER_BUILDKIT=1`)

```
Sep 1 04:01:14 PM  --------------------
Sep 1 04:01:14 PM     1 |     FROM nikolaik/python-nodejs:python3.8-nodejs14 AS base
Sep 1 04:01:14 PM     2 |
Sep 1 04:01:14 PM     3 | >>> WORKDIR /usr/app
Sep 1 04:01:14 PM     4 |
Sep 1 04:01:14 PM     5 |
Sep 1 04:01:14 PM  --------------------
Sep 1 04:01:14 PM  error: failed to solve: failed to compute cache key: mount callback failed on /run/user/1000/containerd-mount003940801: lchown /run/user/1000/containerd-mount003940801/root/.poetry/lib/poetry/_vendor/py2.7/backports/entry_points_selectable.py: invalid argument
```

We haven't changed anything in the code, so I'm not sure what could have happened.

I've seen #30 - which perhaps fixes this since the error message mentions the poetry library

**Comment by owlas** [comment]
We managed to fix this by pinning our docker image to the previous SHA so definitely something has changed in the latest release. 

https://github.com/lightdash/lightdash/pull/403

Thanks to @david-fortini on #29 for the suggestion!

**Comment by nikolaik** [comment]
@owlas I've just rebuilt the images. Do you still see the issue?

**Comment by nikolaik** [comment]
I believe this is solved
