### ISSUE TITLE
bad owner on `/root/.poetry/lib/poetry/_vendor/py2.7/backports/entry_points_selectable.py`

### ISSUE THREAD

**Issue by bshimanuki** [nikolaik/docker-python-nodejs#32]
In `docker.io/nikolaik/python-nodejs:python3.8-nodejs12@sha256:c13a83c8e4216dc6e6c3f07a0f6bd6f940ddca6cf4f8ea50bf179e4efe57c7a9`, the owner of `/root/.poetry/lib/poetry/_vendor/py2.7/backports/entry_points_selectable.py` has a nonexistent uid/gid.
```
root@123456789abc:~/.poetry/lib/poetry/_vendor/py2.7/backports# ls -l
total 16
-rw-r--r-- 1 root       root        212 Aug 19 16:53 __init__.py
drwxr-xr-x 2 root       root       4096 Sep  1 00:21 configparser
-rw-r--r-- 1 1407182137 1059092950 7444 Aug 19 16:55 entry_points_selectable.py
```

(In practice, this means that this image can't be used with a [rootless docker](https://docs.docker.com/engine/security/rootless/#docker-pull-errors) because the uid/gid are above 65535.)

Not sure why only this file; everything else under `/root/.poetry` seems to be fine.

**Comment by nikolaik** [comment]
Thanks for reporting @bshimanuki! The images are now rebuilt and the file with the weird uid/gid should be gone. Do you see the same?

**Comment by bshimanuki** [comment]
Yep! Looks all good now thanks
