### ISSUE TITLE
ODBC header files: how to install them and make a new image

### ISSUE THREAD

**Issue by sant527** [nikolaik/docker-python-nodejs#33]
I dont have ODBC header files on your machine.

I need to install

sudo apt install unixodbc-dev

But how to rebuild the image with this

**Comment by nikolaik** [comment]
> I dont have ODBC header files on your machine.
> 
> I need to install
> 
> sudo apt install unixodbc-dev
> 
> But how to rebuild the image with this

Hey! You need to build your own image and use this as a base image, f.ex using the `latest` tag:

Dockerfile:
```Dockerfile
FROM nikolaik/python-nodejs:latest
RUN sudo apt-get install unixodbc-dev
```
If you create a github repo with something similar to the above `Dockerfile` you can let Docker Hub keep it up to date for you with automated [builds](https://docs.docker.com/docker-hub/builds/).

You can read more [here](https://docs.docker.com/docker-hub/) and [here](https://docs.docker.com/get-started/).
