### ISSUE TITLE
arm64 Support!

### ISSUE THREAD

**Issue by iamkhalidbashir** [nikolaik/docker-python-nodejs#38]

**Comment by esauser** [comment]
This issue was opened almost 2 months ago now, any plans to support this?  And if so, going back through older version permutations?

**Comment by nikolaik** [comment]
> This issue was opened almost 2 months ago now, any plans to support this? And if so, going back through older version permutations?

Plan to support it. Need to investigate if docker buildx is possible to use with docker-python first or if further refactoring is needed.

**Comment by esauser** [comment]
When do you expect to do that?

**Comment by nikolaik** [comment]
> When do you expect to do that?

No estimate, but repo is in a better shape now to add the missing multi arch support using docker buildx

**Comment by lewiswilkins** [comment]
Would be keen for this if possible!

**Comment by fdelucchijr** [comment]
@nikolaik Docker-Pi seems to have support for `--platform` in the build process ([source](https://docker-py.readthedocs.io/en/stable/images.html))

**Comment by douglascorrea** [comment]
Is there any way to build it manually for running in `arm64` but reusing the packages installed in this repo?

**Comment by bananensplit** [comment]
Hey! Are there any updates on this or do you have an estimated timeline for when this will be implemented?
Thanks in advance!

**Comment by theGowda** [comment]
Hi! any updates on this?

**Comment by gaby** [comment]
Any updates on this?

**Comment by nikolaik** [comment]
Hi there and sorry for the lack of updates! I'll try to merge https://github.com/nikolaik/docker-python-nodejs/pull/57 this week, which starts building arm64 for the all the debian variants. I'm holding off on alpine because of [pending unoffical musl+arm64 builds](https://github.com/nodejs/unofficial-builds/pull/59) which is blocked on this: https://github.com/nodejs/node/pull/45756

**Comment by gaby** [comment]
@nikolaik Thank you!

**Comment by nikolaik** [comment]
Just merged #57! let me know if you run into any issues <3 I opened #70 to track arm64 support for the alpine images

**Comment by gaby** [comment]
@nikolaik Thank you, really appreciate it!
