### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by joshua-s** [nikolaik/docker-python-nodejs#5]
It would be great if there could be alpine versions of this image. It is a very popular substitution for Debian because it is very lightweight.

The python image that this project depends on provides an alpine version.

**Comment by nikolaik** [comment]
Agreed! I'll take a look at adding `-alpine` to the docker image build matrix now

**Comment by nikolaik** [comment]
I've merged support now, please test and let me know if you have any issues :hugs:

**Comment by joshua-s** [comment]
Sweet, thanks!
