### ISSUE TITLE
poetry version outdated

### ISSUE THREAD

**Issue by minyoung90** [nikolaik/docker-python-nodejs#56]
I used image python3.9-nodejs16
Recently, I updated my poetry version to 1.3.1
then, that image's poetry is oudated so I can't use it.

please update!

**Comment by nikolaik** [comment]
This seems to have resolved itself
```console
$ docker run -it nikolaik/python-nodejs:python3.9-nodejs16 poetry --version
Poetry (version 1.3.1)
```
