### ISSUE TITLE
Bump GPG key again for python3.6-nodejs12 image

### ISSUE THREAD

**Issue by jacopogreenslade** [nikolaik/docker-python-nodejs#61]
Hi, 

I'm seeing on `nikolaik/python-nodejs:python3.6-nodejs12` that when running `apt-get update` there's an expired key. 

`GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG xxxxxxxxxxxx Yarn Packaging <yarn@dan.cx>`

I ran the workflow a couple of times and it still breaks.

Thanks!

**Comment by jacopogreenslade** [comment]
This seems similar to the closed #58

**Comment by nikolaik** [comment]
Hi there, this image tag is no longer in the current list of supported tags, since both python 3.6 and node v12 is EOL. That means it's no longer receiving any new versions and you should consider rolling to node v14 and python 3.7. Is this possible for your current project?

**Comment by jacopogreenslade** [comment]
Hey, thanks for the fast response!

We are planning to upgrade soon but at the moment we have our hands full. We have found an alternative that works for us right now

**Comment by nikolaik** [comment]
Wonderful, best of luck!
