### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by dobeerman** [nikolaik/docker-python-nodejs#88]
Am I missed something? :thinking: 

```shell
$ docker pull nikolaik/python3.8-nodejs16       

Using default tag: latest
Error response from daemon: pull access denied for nikolaik/python3.8-nodejs16, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by nikolaik** [comment]
I believe you are mixing the image name and the image tag together. It should be:

`docker pull nikolaik/python-nodejs: python3.8-nodejs16`

**Comment by dobeerman** [comment]
> I believe you are mixing the image name and the image tag together. It should be:
> 
> `docker pull nikolaik/python-nodejs: python3.8-nodejs16`
> 
> Are you back on track? 😊

Omg, im back 😂
